my:
  property:
    mainservice:
      init:
        delay: 120
spring:
  application:
    name: epidemic
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    servlet:
      path: /
      load-on-startup: 1
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/epidemic?allowMultiQueries=true #这里还需改进
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        url-pattern: /druid/
        enabled: true
        login-username: qzlzzz
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
            alter-table-allow: false
            select-into-outfile-allow: false
            multi-statement-allow: true
  jdbc:
    template:
      query-timeout: 3
  redis: #此连接应为主从+哨兵 initial为一个端口
    port: 6379
    host: 192.168.119.130
    database: 0
    client-type: lettuce
    lettuce:
      pool:
        max-active: 10
mybatis-plus:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.qzlnode.epidemic.miniprogram.pojo
logging:
  level:
    com:
      qzlnode: info
  file:
    name: C:/log/epidemic.log

